### PR TITLE
improv/add-3g-4g-rrc-channel-types-from-scat: Add missing Qualcomm Diag LTE and WCDMA channel type decoding routines, in order to be able to handle certain recent basebands

### PR DESCRIPTION
**Pull request by p1-mmr**
This should add support for decoding LTE and WCDMA channel types which are not correctly decoded by the tool yet, as outlined by issue #56, and already implemented by the SCAT projet.

As indicated in the newly added source comments, the following code was taked in account in order to do this:
* https://github.com/fgsect/scat/blob/0e1d3a4/parsers/qualcomm/diagwcdmalogparser.py#L259
* https://github.com/fgsect/scat/blob/01d5b81/parsers/qualcomm/diagltelogparser.py#L1207

### CODE REVIEW

**Comment by Melon08P4** [comment]
On Xiaomi Mi 8 we can see only packets from 2G network. No from 3G and 4G

**Comment by Melon08P4** [comment]
Hello, on Xiaomi Mi 8 I have another problem with diffrent DIAG_CMD like below:
[<] Received response 152 of length 62: b'\x01\x00\x00\x01\x00\x00\x00\x10\x003\x003\x00/A\t\x89\xbfq;"\xf3\x00\x84(\x1f\x00z\x0bC\x00P\x8e _\x00\x98\x00\xc2\xa8\x11!\x91!\x010 8\xb8\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01'
[<] Received response 152 of length 62: b'\x01\x00\x00\x01\x00\x00\x00\x10\x003\x003\x00/A\x0ce\xcfq;"\xf3\x00\x84(\x1f\x00z\x0bC\x00P\xa6Q\x93D3\x00\x0f\x10\xc0-\xb64\x00\x86\x11(\x16F\x1e\xe1\xd0\x00\x00\x00\x00\x00\x00\x00\x00\x00'
[<] Received response 152 of length 51: b'\x01\x00\x00\x01\x00\x00\x00\x10\x00(\x00(\x00/A\x0c\xb9\xd1q;"\xf3\x00\x80\x00\x14\x00z\x0bC\x00\xfe7\xfc\x16\x08\xc0?\xeb\xdb\xd0\x00\x01@\x01\x00`<\xd0\xa8\xe0'
[<] Received response 152 of length 62: b'\x01\x00\x00\x01\x00\x00\x00\x10\x003\x003\x00/A\x0e}\xdfq;"\xf3\x00\x84(\x1f\x00z\x0bC\x00P\xc2\xb1\x80\x19h\x98\x02!\xd0\x84;\xa2\x08WF\x11n\x90&\xad(B:`\x89t\xe1\x0b*\x02'
[<] Received response 152 of length 48: b'\x01\x00\x00\x01\x00\x00\x00\x10\x00%\x00%\x00/A\x19\r=r;"\xf3\x00\x83\x01\x11\x00z\x0bC\x00\xdcb\xbe\x13\x08\xf7\xc0B\x00\x00\x02\x00\x03\xc3\xd1\x92\x80'
[<] Received response 152 of length 38: b'\x01\x00\x00\x01\x00\x00\x00\x10\x00\x1b\x00\x1b\x00/A\x1e\x9dar;"\xf3\x00\x81\x02\x07\x00z\x0bC\x00\x93Ba\x05\xa2@\x80'

Can we commit it too ?

**Comment by p1-mmr** [comment]
It's true that I could add support for message type `DIAG_MULTI_RADIO_CMD_F` as outlined in issue #36, will look at it tomorrow.

**Comment by Melon08P4** [comment]
Ok, thank. Waiting for feedback and i Will test it immediately

**Comment by Melon08P4** [comment]
> Ok, thank. Waiting for feedback and i Will test it immediately

It works but most packets are malwared. Probably 4G log types should be modified also

**Comment by p1-mmr** [comment]
I added another commit, it should be better now.

**Comment by Melon08P4** [comment]
It works better but i still have some problems with Mal packets and I have
a lot of rrc rejects

wt., 18 maj 2021 o 13:34 Marin ***@***.***> napisał(a):

**Comment by p1-mmr** [comment]
Ok, can you plese run the following command (or at least use the `--dlf-dump` flag) in order to generate a `.DLF` file that will be useful for debugging purposes:

```
./qcsuper.py --adb --dlf-dump /tmp/output_file.dlf
```

Before stopping the command, do what you would usually do to test the tool (e.g generate a few cell traffic, switch radio access technologies, wait a few minutes) and then either send the produced `.dlf` file to this issue, or send it aｔ mmr at p1sec ｄｏｔ com?

This would be useful to understand better the issue. Thank you!

**Comment by Melon08P4** [comment]
I have send it to ***@***.***

BR,
Arek

wt., 18 maj 2021 o 14:09 Marin ***@***.***> napisał(a):

**Comment by p1-mmr** [comment]
Thank you, made another change which seems to decode the LTE packet correctly.

**Comment by Melon08P4** [comment]
Hi,

Yes, looks fine! Thank you, now is my part to get it to txt instead of pcap
:)

wt., 18 maj 2021 o 15:07 Marin ***@***.***> napisał(a):

**Comment by Melon08P4** [comment]
Are you planning to add more ? For example to decode MCC, MNC, TAC, Cell ID
?

wt., 18 maj 2021 o 15:07 Marin ***@***.***> napisał(a):

**Comment by p1-mmr** [comment]
Hello,

>Yes, looks fine! Thank you, now is my part to get it to txt instead of pcap

Regarding this matter, you may be interested in using the `tshark` command line tool (which is ofted bundled with Wireshark, or available as a separate distribution package depending on your platform) in order to convert the traffic to text, JSON, XML...

For exemple, in order to obtain a verbose text output from a PCAP file, you may use:

```
tshark -r sample_2g_3g_4g_xperia_with_sib_and_nas.pcap.gz -VV
```

In order to obtain different flavours of JSON output (`ek` means ElasticSearch - beware, certain variants of these formats may sometimes produce JSON entries with identical keys in the same object):

```
tshark -r sample_2g_3g_4g_xperia_with_sib_and_nas.pcap.gz -T json
tshark -r sample_2g_3g_4g_xperia_with_sib_and_nas.pcap.gz -T ek
```

In order to obtain XML output:

```
tshark -r sample_2g_3g_4g_xperia_with_sib_and_nas.pcap.gz -T pdml
```

In order to obtain CSV output with only a given packet field, here an IP address (use "Right click > Prepare as filter > Selected" in Wireshark on a GUI field in order to know the text field name associated to a visible GUI field, when there is one, or look at the other formats output, or consult the filters reference from Wireshark: https://www.wireshark.org/docs/dfref/), you may use:

```
tshark -r sample_2g_3g_4g_xperia_with_sib_and_nas.pcap.gz -T fields -e ip.addr -E header=y -E separator=, -E quote=d -E 'aggregator=|'
```

If you are wishing to have full programmatic control over what you do, you may use the Pycrate Python library which is able to decode QCSuper output (it is also used by QCSuper and developed by us): https://github.com/P1sec/pycrate/wiki/Using-the-pycrate-asn1-runtime#the-umts-and-lte-rrc-protocols

Without using an external tool, I think that the `--decoded-sibs-dump` option of QCSuper may interest you in certain cases (and that you may want to use the `--reassemble-sibs` or `--decrypt-nas` flags in any way, and they will have certain identifiers to appear visibly in the generated PCAP files)

```
  --decoded-sibs-dump   Print decoded SIBs to stdout (experimental, requires
                        pycrate).
```

```
  --reassemble-sibs     Include reassembled UMTS SIBs as supplementary frames,
                        also embedded fragmented in RRC frames.
  --decrypt-nas         Include unencrypted LTE NAS as supplementary frames,
                        also embedded ciphered in RRC frames.
```

>Are you planning to add more ? For example to decode MCC, MNC, TAC, Cell ID

The purpose of QCSuper is to provide a Diag client, and more specifically to produce PCAP files which can be leveraged with various other tools when it comes to capturing raw mobile protocol radio frames.

Regards,

**Pull request merged**
